import {ChloieoGame} from './platformer/game.js';
export let runner = null;
import {state,reset} from './state.js';
import {assets,pic,icon,preload,installFallbacks} from './assets.js';
import {audio} from './audio.js';
import {animate,sparkle,flyToTarget,confetti,wait} from './animations.js';
import {fruitGarden} from './activities/fruitGarden.js';
import {beeMeadow} from './activities/beeMeadow.js';
import {dinoFeed} from './activities/dinoFeed.js';
import {picnic} from './activities/picnic.js';
const activities=[fruitGarden,beeMeadow,dinoFeed,picnic];
const scene=document.querySelector('#scene'),game=document.querySelector('#game');
let rounds=[],round=null;
const chloe=(pose='point')=>`<div class="chloe-wrap"><div class="chloe chloe-${pose}" role="img" aria-label="Chloe ${pose==='happy'?'celebrating':pose==='wave'?'waving':'helping you'}" style="background-image:url('${assets.chloe}')"></div><div class="chloe-shadow"></div></div>`;
function updateHeader(){document.querySelector('#home').innerHTML=icon('home');document.querySelector('#home').hidden=state.screen==='home';document.querySelector('#sound').innerHTML=icon(state.soundEnabled?'sound':'muted');document.querySelector('#sound').setAttribute('aria-label',state.soundEnabled?'Turn sound off':'Turn sound on');document.querySelector('#sound').setAttribute('aria-pressed',String(state.soundEnabled));document.querySelector('#stickers').innerHTML=activities.map(a=>`<span class="sticker ${state.stickers.includes(a.id)?'earned':''}" aria-label="${a.name} sticker ${state.stickers.includes(a.id)?'earned':'to collect'}">${pic(a.sticker)}</span>`).join('');}
function home(){runner?.destroy();runner=null;audio.stop();reset();round=null;game.dataset.theme='home';updateHeader();scene.innerHTML=`<div class="home-scene">${chloe('wave')}<div class="home-copy"><span class="eyebrow">A LITTLE WORLD OF WONDER</span><h1>Chloe’s<br><span>Little Adventure</span></h1><p>Find. Count. Munch. Smile.</p><div class="home-buttons"><button class="play-button" data-action="play" aria-label="Let's Play Numbers">${icon('play')}<span>Let's Play Numbers</span></button><button class="play-button chloieo-button" data-action="chloieo" aria-label="Let's Play Chloieo!">${icon('play')}<span>Let's Play Chloieo!</span></button><button class="play-button karts-button" data-action="karts" aria-label="Let's Play Chlio Karts!">${icon('play')}<span>Let's Play Chlio Karts!</span></button><button class="play-button fishing-button" data-action="fishing" aria-label="Let's Play Fishing!">${icon('play')}<span>Let's Play Fishing!</span></button></div><div class="home-friends" aria-hidden="true">${pic('apple')}${pic('bee')}${pic('dinosaur')}</div></div><span class="ground-flower flower-a" aria-hidden="true">✿</span><span class="ground-flower flower-b" aria-hidden="true">✿</span></div>`;}
function start(){if(state.portrait)return;runner?.destroy();runner=null;audio.stop();audio.unlock();audio.startMusic();reset('activity');rounds=activities.map(a=>a.makeRounds());renderRound();}
function startChloieo(){if(state.portrait)return;runner?.destroy();audio.stop();audio.unlock();audio.startMusic();reset('platformer');game.dataset.theme='platformer';updateHeader();runner=new ChloieoGame(scene,{onHome:home,isPaused:()=>state.portrait||document.hidden});}
async function startKarts(){if(state.portrait)return;runner?.destroy();runner=null;audio.stop();audio.unlock();audio.startMusic();reset('karts');const session=state.session;game.dataset.theme='karts';updateHeader();scene.innerHTML='<div class="kart-loading" role="status">Getting Chloe’s kart ready…</div>';try{const {ChlioKartsGame}=await import('./karts/game.js?v=3.0.1');if(state.session!==session)return;runner=new ChlioKartsGame(scene,{onHome:home,isPaused:()=>state.portrait||document.hidden});}catch{if(state.session!==session)return;scene.innerHTML='<div class="kart-loading"><p>The kart couldn’t load. Let’s try again!</p><button class="play-button" data-action="home">Home</button></div>';}}
async function startFishing(){if(state.portrait)return;runner?.destroy();runner=null;audio.stop();audio.unlock();audio.startMusic();reset('fishing');const session=state.session;game.dataset.theme='fishing';updateHeader();scene.innerHTML='<div class="fish-loading" role="status">Getting Chloe’s fishing boat ready…</div>';try{const {ChloeFishingGame}=await import('./fishing/game.js?v=4.0.0');if(state.session!==session)return;runner=new ChloeFishingGame(scene,{isPaused:()=>state.portrait||document.hidden});}catch{if(state.session!==session)return;scene.innerHTML='<div class="fish-loading"><p>The fishing boat couldn’t load. Let’s try again!</p><button class="play-button" data-action="home">Home</button></div>';}}
function renderRound(){state.screen='activity';state.interactionLocked=false;state.count=0;const a=activities[state.activityIndex];round=rounds[state.activityIndex][state.roundIndex];game.dataset.theme=a.id;updateHeader();scene.innerHTML=`<div class="activity-scene sceneFadeIn">${chloe()}<div class="activity"><div class="activity-heading"><span class="eyebrow">${a.name}</span><div class="round-dots" aria-label="Round ${state.roundIndex+1} of 3">${[0,1,2].map(i=>`<i class="${i<=state.roundIndex?'done':''}"></i>`).join('')}</div></div><button class="prompt" data-action="repeat" aria-label="Hear the instruction again"><h2>${a.prompt(round)}</h2><span class="listen-icon">${icon('sound')}</span></button><div class="activity-body">${a.render(round)}</div></div></div>`;audio.say(a.prompt(round));}
async function success(el){state.interactionLocked=true;animate(el,'correctBounce');sparkle(el);document.querySelector('.chloe')?.classList.add('chloe-happy');audio.effect();const session=state.session;if(!await wait(850,session))return;state.roundIndex++;if(state.roundIndex<3){renderRound();return;}const a=activities[state.activityIndex];state.stickers.push(a.id);updateHeader();confetti();scene.innerHTML=`<div class="award-scene">${chloe('happy')}<div class="award-copy"><span class="eyebrow">A LITTLE DISCOVERY!</span><div class="big-sticker">${pic(a.sticker)}</div><h2>Lovely job!</h2></div></div>`;const praise=audio.say('Lovely job!');if(!await wait(1300,session))return;await praise;if(session!==state.session)return;state.activityIndex++;state.roundIndex=0;if(state.activityIndex===activities.length)finish();else renderRound();}
function finish(){state.screen='celebration';state.interactionLocked=false;game.dataset.theme='home';updateHeader();scene.innerHTML=`<div class="final-scene">${chloe('happy')}<div class="final-copy"><span class="eyebrow">WHAT A LOVELY ADVENTURE</span><h2>You did it!</h2><p>Four little discoveries. All yours.</p><div class="final-stickers">${activities.map(a=>`<div class="sticker earned" aria-label="${a.name} sticker">${pic(a.sticker)}</div>`).join('')}</div><button class="play-button" data-action="play">${icon('replay')}<span>Play again</span></button><button class="home-text" data-action="home">Home</button></div></div>`;confetti();audio.say('You did it! What a lovely adventure!');}
async function answer(button){const a=activities[state.activityIndex];if(a===fruitGarden){if(button.dataset.answer!==round.fruit){animate(button,'wrongWiggle');return;}await success(button);}else if(a===beeMeadow){if(Number(button.dataset.answer)!==round.count){animate(button,'wrongWiggle');return;}state.interactionLocked=true;const session=state.session;const bees=[...scene.querySelectorAll('.bee')];for(let i=0;i<bees.length;i++){bees[i].classList.add('counted');bees[i].querySelector('.bee-count').textContent=i+1;animate(bees[i],'gentleBounce');const spoken=audio.say(String(i+1));if(!await wait(650,session))return;await spoken;if(session!==state.session)return;}await success(button);}}
async function food(button){if(button.dataset.food!==round.fruit){animate(button,'wrongWiggle');return;}if(button.disabled)return;button.disabled=true;state.count++;state.interactionLocked=true;const session=state.session,target=scene.querySelector('#target');flyToTarget(button,target);const slots=scene.querySelectorAll('.quantity-slots i');slots[state.count-1]?.classList.add('filled');const spoken=audio.say(String(state.count));audio.effect('munch');if(!await wait(530,session))return;await spoken;if(session!==state.session)return;animate(target,'dinoMunch');if(state.count>=round.count)await success(target);else state.interactionLocked=false;}
function tap(button){if(state.portrait||!button||button.disabled)return;const action=button.dataset.action;if(button.id==='sound'){state.soundEnabled=audio.toggle();if(state.soundEnabled){audio.unlock();if(state.screen==='activity')audio.say(activities[state.activityIndex].prompt(round));}updateHeader();return;}if(button.id==='home'||action==='home'){home();return;}if(state.interactionLocked)return;if(action==='play'){start();return;}if(action==='chloieo'){startChloieo();return;}if(action==='karts'){startKarts();return;}if(action==='fishing'){startFishing();return;}if(action==='repeat'){audio.say(activities[state.activityIndex].prompt(round));return;}if(state.screen!=='activity')return;if(button.dataset.answer!==undefined)answer(button);else if(button.dataset.food)food(button);else if(button.dataset.bee!==undefined){animate(button,'gentleBounce');audio.effect('tap');}}
// A tap must end on its original button. Secondary pointers never submit actions.
let pointer=null;
document.addEventListener('pointerdown',e=>{if(e.isPrimary===false)return;pointer={id:e.pointerId,button:e.target.closest('button'),x:e.clientX,y:e.clientY};});
document.addEventListener('pointerup',e=>{if(!pointer||e.isPrimary===false||pointer.id!==e.pointerId)return;const p=pointer;pointer=null;if(Math.hypot(e.clientX-p.x,e.clientY-p.y)>24)return;if(e.target.closest('button')!==p.button)return;tap(p.button);});
document.addEventListener('pointercancel',()=>pointer=null);
// Native assistive-technology / keyboard activation, without duplicate pointer clicks.
document.addEventListener('click',e=>{if(e.detail===0)tap(e.target.closest('button'));});
function orientation(){state.portrait=innerHeight>innerWidth;document.querySelector('#orientation').hidden=!state.portrait;scene.inert=state.portrait;document.querySelector('header').inert=state.portrait;audio.setPaused('orientation',state.portrait);}
document.addEventListener('visibilitychange',()=>audio.setPaused('hidden',document.hidden));
window.addEventListener('resize',orientation);installFallbacks();preload();audio.preload();home();orientation();
