require('fs').mkdirSync('work',{recursive:true});
const assert=require('assert/strict');
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL==='chromium'?undefined:(process.env.BROWSER_CHANNEL||'msedge')});const page=await browser.newPage({viewport:{width:844,height:390},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));const getState=()=>page.evaluate(async()=>({... (await import('/js/state.js')).state}));
await page.goto('http://127.0.0.1:4173');await page.evaluate(async()=>window.qaState=(await import('/js/state.js')).state);await page.waitForTimeout(350);await page.screenshot({path:'work/home.png'});
await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('#orientation').isVisible(),true);assert.equal((await getState()).screen,'home');await page.setViewportSize({width:844,height:390});await page.locator('[data-action=play]').tap();await page.waitForTimeout(350);
const layouts=[];
async function checkLayout(label){for(const [width,height] of [[844,390],[852,393],[915,412],[1024,768],[667,375]]){await page.setViewportSize({width,height});await page.waitForTimeout(50);const data=await page.evaluate(()=>({w:innerWidth,h:innerHeight,sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight,targets:[...document.querySelectorAll('.fruit-choice,.food,.number-choice,.bee,.play-button')].filter(e=>getComputedStyle(e).visibility!=='hidden').map(e=>{const r=e.getBoundingClientRect();return {text:e.getAttribute('aria-label'),x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom};})}));assert.equal(data.sw,width,`${label} horizontal scroll`);assert.equal(data.sh,height,`${label} vertical scroll`);for(const b of data.targets){assert.ok(b.width>=71&&b.height>=71,`${label} target too small ${JSON.stringify(b)}`);assert.ok(b.x>=0&&b.y>=0&&b.right<=width+1&&b.bottom<=height+1,`${label} target cropped ${width}: ${JSON.stringify(b)}`);}layouts.push(`${label} ${width}x${height}`);}await page.setViewportSize({width:844,height:390});await page.waitForTimeout(100);await page.screenshot({path:`work/${label}.png`});}
await checkLayout('fruit');
const target=await page.locator('.match-prompt img').getAttribute('data-asset');await page.locator(`.fruit-choice:not([data-answer="${target}"])`).first().tap();assert.equal((await getState()).roundIndex,0);assert.equal((await getState()).interactionLocked,false);
await page.locator('#sound').tap();assert.equal((await getState()).soundEnabled,false);await page.locator('#sound').tap();assert.equal((await getState()).soundEnabled,true);
// Two pointer contacts: only the primary tap can submit; rapid repeat must lock.
await page.locator(`[data-answer="${target}"]`).evaluate(el=>{for(const isPrimary of [false,true,true]){const o={bubbles:true,pointerId:isPrimary?1:2,isPrimary,clientX:10,clientY:10};el.dispatchEvent(new PointerEvent('pointerdown',o));el.dispatchEvent(new PointerEvent('pointerup',o));}});
assert.equal((await getState()).interactionLocked,true);await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1100);assert.equal((await getState()).roundIndex,0);assert.equal(await page.locator('#orientation').isVisible(),true);await page.setViewportSize({width:844,height:390});await page.waitForFunction(()=>window.qaState.roundIndex===1);
const seen=new Set(['fruit']);
for(let safety=0;safety<80;safety++){const s=await getState();if(s.screen==='celebration')break;if(s.interactionLocked){await page.waitForTimeout(250);continue;}const names=['fruit','bee','dinosaur','picnic'];const label=names[s.activityIndex];if(!seen.has(label)){await checkLayout(label);seen.add(label);}const old=`${s.activityIndex}-${s.roundIndex}`;
if(s.activityIndex===0){const f=await page.locator('.match-prompt img').getAttribute('data-asset');await page.locator(`[data-answer="${f}"]`).tap();}
else if(s.activityIndex===1){const n=await page.locator('.bee').count();await page.locator(`.number-choice:not([data-answer="${n}"])`).first().tap();assert.equal((await getState()).interactionLocked,false);await page.locator(`.number-choice[data-answer="${n}"]`).tap();}
else{const f=await page.locator('.quantity-prompt>img').getAttribute('data-asset');const n=await page.locator('.quantity-slots i').count();if(s.activityIndex===3){await page.locator(`.food:not([data-food="${f}"])`).first().tap();assert.equal((await getState()).count,0);}for(let j=0;j<n;j++){await page.locator(`.food[data-food="${f}"]:not(:disabled)`).first().tap();assert.equal((await getState()).count,j+1);if(j<n-1)await page.waitForFunction(()=>!window.qaState.interactionLocked);}}
await page.waitForFunction(old=>{const s=window.qaState;return s.screen==='celebration'||(!s.interactionLocked&&`${s.activityIndex}-${s.roundIndex}`!==old);},old,{timeout:12000});}
assert.equal((await getState()).screen,'celebration');assert.equal((await getState()).stickers.length,4);await checkLayout('celebration');await page.locator('[data-action=play]').tap();let s=await getState();assert.equal(s.roundIndex,0);assert.equal(s.activityIndex,0);assert.deepEqual(s.stickers,[]);await page.locator('#home').tap();assert.equal((await getState()).screen,'home');
// Leaving during a pending success cannot advance the home screen.
await page.locator('[data-action=play]').tap();await page.waitForTimeout(350);const f=await page.locator('.match-prompt img').getAttribute('data-asset');await page.locator(`[data-answer="${f}"]`).tap();await page.locator('#home').tap();await page.waitForTimeout(1300);assert.equal((await getState()).screen,'home');assert.equal((await getState()).activityIndex,0);assert.deepEqual(errors,[]);
console.log(JSON.stringify({result:'PASS',checks:['Full 12-round flow','Wrong answers in three applicable activities','Counting 1–5','Rapid repeated and non-primary pointer taps','Orientation pause retains progress','Sound on/off','Replay resets session','Home cancels pending transitions','No runtime errors',...layouts]},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
