import { build } from 'esbuild';
import { copyFile } from 'node:fs/promises';
await build({
  entryPoints:['js/vendor/three-entry.js'],bundle:true,minify:true,
  format:'esm',platform:'browser',target:'es2020',legalComments:'inline',
  outfile:'js/vendor/three.js',
  banner:{js:'/* Three.js 0.186.1 — MIT license: THREE-LICENSE.txt. Generated by npm run vendor:karts. */'}
});
await copyFile('node_modules/three/LICENSE','js/vendor/THREE-LICENSE.txt');
